export const ELEVENLABS_SCRIBE_LANGUAGES = [
  { value: "auto", label: "Automatic" },
  { value: "afr", label: "Afrikaans" },
  { value: "amh", label: "Amharic" },
  { value: "ara", label: "Arabic" },
  { value: "hye", label: "Armenian" },
  { value: "asm", label: "Assamese" },
  { value: "ast", label: "Asturian" },
  { value: "aze", label: "Azerbaijani" },
  { value: "bel", label: "Belarusian" },
  { value: "ben", label: "Bengali" },
  { value: "bos", label: "Bosnian" },
  { value: "bul", label: "Bulgarian" },
  { value: "mya", label: "Burmese" },
  { value: "yue", label: "Cantonese" },
  { value: "cat", label: "Catalan" },
  { value: "ceb", label: "Cebuano" },
  { value: "nya", label: "Chichewa" },
  { value: "hrv", label: "Croatian" },
  { value: "ces", label: "Czech" },
  { value: "dan", label: "Danish" },
  { value: "nld", label: "Dutch" },
  { value: "eng", label: "English" },
  { value: "est", label: "Estonian" },
  { value: "fil", label: "Filipino" },
  { value: "fin", label: "Finnish" },
  { value: "fra", label: "French" },
  { value: "ful", label: "Fulah" },
  { value: "glg", label: "Galician" },
  { value: "lug", label: "Ganda" },
  { value: "kat", label: "Georgian" },
  { value: "deu", label: "German" },
  { value: "ell", label: "Greek" },
  { value: "guj", label: "Gujarati" },
  { value: "hau", label: "Hausa" },
  { value: "heb", label: "Hebrew" },
  { value: "hin", label: "Hindi" },
  { value: "hun", label: "Hungarian" },
  { value: "isl", label: "Icelandic" },
  { value: "ibo", label: "Igbo" },
  { value: "ind", label: "Indonesian" },
  { value: "gle", label: "Irish" },
  { value: "ita", label: "Italian" },
  { value: "jpn", label: "Japanese" },
  { value: "jav", label: "Javanese" },
  { value: "kea", label: "Kabuverdianu" },
  { value: "kan", label: "Kannada" },
  { value: "kaz", label: "Kazakh" },
  { value: "khm", label: "Khmer" },
  { value: "kor", label: "Korean" },
  { value: "kur", label: "Kurdish" },
  { value: "kir", label: "Kyrgyz" },
  { value: "lao", label: "Lao" },
  { value: "lav", label: "Latvian" },
  { value: "lin", label: "Lingala" },
  { value: "lit", label: "Lithuanian" },
  { value: "luo", label: "Luo" },
  { value: "ltz", label: "Luxembourgish" },
  { value: "mkd", label: "Macedonian" },
  { value: "msa", label: "Malay" },
  { value: "mal", label: "Malayalam" },
  { value: "mlt", label: "Maltese" },
  { value: "zho", label: "Mandarin Chinese" },
  { value: "mri", label: "Māori" },
  { value: "mar", label: "Marathi" },
  { value: "mon", label: "Mongolian" },
  { value: "nep", label: "Nepali" },
  { value: "nso", label: "Northern Sotho" },
  { value: "nor", label: "Norwegian" },
  { value: "oci", label: "Occitan" },
  { value: "ori", label: "Odia" },
  { value: "pus", label: "Pashto" },
  { value: "fas", label: "Persian" },
  { value: "pol", label: "Polish" },
  { value: "por", label: "Portuguese" },
  { value: "pan", label: "Punjabi" },
  { value: "ron", label: "Romanian" },
  { value: "rus", label: "Russian" },
  { value: "srp", label: "Serbian" },
  { value: "sna", label: "Shona" },
  { value: "snd", label: "Sindhi" },
  { value: "slk", label: "Slovak" },
  { value: "slv", label: "Slovenian" },
  { value: "som", label: "Somali" },
  { value: "spa", label: "Spanish" },
  { value: "swa", label: "Swahili" },
  { value: "swe", label: "Swedish" },
  { value: "tam", label: "Tamil" },
  { value: "tgk", label: "Tajik" },
  { value: "tel", label: "Telugu" },
  { value: "tha", label: "Thai" },
  { value: "tur", label: "Turkish" },
  { value: "ukr", label: "Ukrainian" },
  { value: "umb", label: "Umbundu" },
  { value: "urd", label: "Urdu" },
  { value: "uzb", label: "Uzbek" },
  { value: "vie", label: "Vietnamese" },
  { value: "cym", label: "Welsh" },
  { value: "wol", label: "Wolof" },
  { value: "xho", label: "Xhosa" },
  { value: "zul", label: "Zulu" }
] as const;

export type ElevenLabsScribeLanguage =
  typeof ELEVENLABS_SCRIBE_LANGUAGES[number]["value"];

export const ELEVENLABS_SCRIBE_LANGUAGE_CODES = ELEVENLABS_SCRIBE_LANGUAGES.map(
  ({ value }) => value
) as [ElevenLabsScribeLanguage, ...ElevenLabsScribeLanguage[]];
