export const RECORDED_SPEECH_SAMPLE_RATE = 16_000;
export const MAX_RECORDED_SPEECH_SECONDS = 300;
export const MAX_RECORDED_SPEECH_AUDIO_BYTES =
  RECORDED_SPEECH_SAMPLE_RATE * MAX_RECORDED_SPEECH_SECONDS * Float32Array.BYTES_PER_ELEMENT;
